version: "3.8"

services:
  db:
      image: postgres:16
      container_name: "chat_db"
      env_file:
        - .env_dev
      ports:
        - "5432:5432"

  redis:
    image: redis:7
    container_name: chat_redis
    ports:
      - "6379:6379"

  celery:
    image: chat_celery
    build:
      context: .
    container_name: chat_celery
    command: sh -c "celery -A core.tasks.celery_config:celery worker -l INFO"
    env_file:
      - .env_dev
    depends_on:
      - redis


  chat_service:
    image: chat_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_dev
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000



  prometheus:
     image: prom/prometheus:v2.43.0
     container_name: prometheus
     volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheusdata:/prometheus
     restart: unless-stopped
     ports:
       - 9090:9090

  grafana:
     image: grafana/grafana:9.4.7
     container_name: grafana
     volumes:
       - grafanadata:/var/lib/grafana
     restart: unless-stopped
     ports:
       - 3000:3000

volumes:
  postgres:
  grafanadata:
  prometheusdata: