"""init

Revision ID: e4221d875527
Revises: 68bbec2a2f9b
Create Date: 2024-04-13 18:46:41.822750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4221d875527'
down_revision: Union[str, None] = '68bbec2a2f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time_send', sa.TIME(), nullable=False))
    op.drop_column('messages', 'time_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time_sent', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'time_send')
    # ### end Alembic commands ###
